# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster.proto',
  package='singa',
  serialized_pb=_b('\n\rcluster.proto\x12\x05singa\"\xa2\x04\n\x0c\x43lusterProto\x12\x16\n\x0enworker_groups\x18\x01 \x01(\x05\x12\x16\n\x0enserver_groups\x18\x02 \x01(\x05\x12\x1d\n\x12nworkers_per_group\x18\x03 \x01(\x05:\x01\x31\x12\x1d\n\x12nservers_per_group\x18\x04 \x01(\x05:\x01\x31\x12\x1d\n\x12nworkers_per_procs\x18\x05 \x01(\x05:\x01\x31\x12\x1d\n\x12nservers_per_procs\x18\x06 \x01(\x05:\x01\x31\x12\x12\n\x08hostfile\x18\n \x01(\t:\x00\x12%\n\x16server_worker_separate\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x18\n\nstart_port\x18\r \x01(\x05:\x04\x36\x37\x32\x33\x12\x11\n\tworkspace\x18\x0e \x02(\t\x12\x0f\n\x07log_dir\x18\x0f \x01(\t\x12&\n\x0ezookeeper_host\x18\x10 \x01(\t:\x0elocalhost:2181\x12\x1a\n\x0cstub_timeout\x18\x1e \x01(\x05:\x04\x35\x30\x30\x30\x12\x1c\n\x0eworker_timeout\x18\x1f \x01(\x05:\x04\x35\x30\x30\x30\x12\x1c\n\x0eserver_timeout\x18  \x01(\x05:\x04\x35\x30\x30\x30\x12\x1b\n\rserver_update\x18( \x01(\x08:\x04true\x12\x1a\n\x0cshare_memory\x18) \x01(\x08:\x04true\x12\x1c\n\tbandwidth\x18\x32 \x01(\x05:\t134217728\x12\x16\n\tpoll_time\x18\x33 \x01(\x05:\x03\x31\x30\x30\"E\n\x0eServerTopology\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x15\n\rsync_interval\x18\x02 \x01(\x05\x12\x10\n\x08neighbor\x18\x03 \x03(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLUSTERPROTO = _descriptor.Descriptor(
  name='ClusterProto',
  full_name='singa.ClusterProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nworker_groups', full_name='singa.ClusterProto.nworker_groups', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nserver_groups', full_name='singa.ClusterProto.nserver_groups', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nworkers_per_group', full_name='singa.ClusterProto.nworkers_per_group', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nservers_per_group', full_name='singa.ClusterProto.nservers_per_group', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nworkers_per_procs', full_name='singa.ClusterProto.nworkers_per_procs', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nservers_per_procs', full_name='singa.ClusterProto.nservers_per_procs', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostfile', full_name='singa.ClusterProto.hostfile', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_worker_separate', full_name='singa.ClusterProto.server_worker_separate', index=7,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_port', full_name='singa.ClusterProto.start_port', index=8,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=6723,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='singa.ClusterProto.workspace', index=9,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_dir', full_name='singa.ClusterProto.log_dir', index=10,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zookeeper_host', full_name='singa.ClusterProto.zookeeper_host', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("localhost:2181").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stub_timeout', full_name='singa.ClusterProto.stub_timeout', index=12,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worker_timeout', full_name='singa.ClusterProto.worker_timeout', index=13,
      number=31, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_timeout', full_name='singa.ClusterProto.server_timeout', index=14,
      number=32, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_update', full_name='singa.ClusterProto.server_update', index=15,
      number=40, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='share_memory', full_name='singa.ClusterProto.share_memory', index=16,
      number=41, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='singa.ClusterProto.bandwidth', index=17,
      number=50, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=134217728,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poll_time', full_name='singa.ClusterProto.poll_time', index=18,
      number=51, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=571,
)


_SERVERTOPOLOGY = _descriptor.Descriptor(
  name='ServerTopology',
  full_name='singa.ServerTopology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='singa.ServerTopology.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_interval', full_name='singa.ServerTopology.sync_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='singa.ServerTopology.neighbor', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=642,
)

DESCRIPTOR.message_types_by_name['ClusterProto'] = _CLUSTERPROTO
DESCRIPTOR.message_types_by_name['ServerTopology'] = _SERVERTOPOLOGY

ClusterProto = _reflection.GeneratedProtocolMessageType('ClusterProto', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERPROTO,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:singa.ClusterProto)
  ))
_sym_db.RegisterMessage(ClusterProto)

ServerTopology = _reflection.GeneratedProtocolMessageType('ServerTopology', (_message.Message,), dict(
  DESCRIPTOR = _SERVERTOPOLOGY,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:singa.ServerTopology)
  ))
_sym_db.RegisterMessage(ServerTopology)


# @@protoc_insertion_point(module_scope)
