// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vs.proto

public final class Vs {
  private Vs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VisualConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VisualConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string charts = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getChartsList();
    /**
     * <code>repeated string charts = 1;</code>
     */
    int getChartsCount();
    /**
     * <code>repeated string charts = 1;</code>
     */
    java.lang.String getCharts(int index);
    /**
     * <code>repeated string charts = 1;</code>
     */
    com.google.protobuf.ByteString
        getChartsBytes(int index);

    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    java.util.List<Vs.VisualConfig.PicPlot> 
        getPicsList();
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    Vs.VisualConfig.PicPlot getPics(int index);
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    int getPicsCount();
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    java.util.List<? extends Vs.VisualConfig.PicPlotOrBuilder> 
        getPicsOrBuilderList();
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    Vs.VisualConfig.PicPlotOrBuilder getPicsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code VisualConfig}
   */
  public static final class VisualConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VisualConfig)
      VisualConfigOrBuilder {
    // Use VisualConfig.newBuilder() to construct.
    private VisualConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VisualConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VisualConfig defaultInstance;
    public static VisualConfig getDefaultInstance() {
      return defaultInstance;
    }

    public VisualConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VisualConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                charts_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              charts_.add(bs);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pics_ = new java.util.ArrayList<Vs.VisualConfig.PicPlot>();
                mutable_bitField0_ |= 0x00000002;
              }
              pics_.add(input.readMessage(Vs.VisualConfig.PicPlot.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          charts_ = charts_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pics_ = java.util.Collections.unmodifiableList(pics_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Vs.internal_static_VisualConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Vs.internal_static_VisualConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Vs.VisualConfig.class, Vs.VisualConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<VisualConfig> PARSER =
        new com.google.protobuf.AbstractParser<VisualConfig>() {
      public VisualConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisualConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VisualConfig> getParserForType() {
      return PARSER;
    }

    public interface PicPlotOrBuilder extends
        // @@protoc_insertion_point(interface_extends:VisualConfig.PicPlot)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string dataname = 1;</code>
       */
      boolean hasDataname();
      /**
       * <code>required string dataname = 1;</code>
       */
      java.lang.String getDataname();
      /**
       * <code>required string dataname = 1;</code>
       */
      com.google.protobuf.ByteString
          getDatanameBytes();

      /**
       * <code>required string scirptname = 2;</code>
       */
      boolean hasScirptname();
      /**
       * <code>required string scirptname = 2;</code>
       */
      java.lang.String getScirptname();
      /**
       * <code>required string scirptname = 2;</code>
       */
      com.google.protobuf.ByteString
          getScirptnameBytes();

      /**
       * <code>required string picname = 3;</code>
       */
      boolean hasPicname();
      /**
       * <code>required string picname = 3;</code>
       */
      java.lang.String getPicname();
      /**
       * <code>required string picname = 3;</code>
       */
      com.google.protobuf.ByteString
          getPicnameBytes();
    }
    /**
     * Protobuf type {@code VisualConfig.PicPlot}
     */
    public static final class PicPlot extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:VisualConfig.PicPlot)
        PicPlotOrBuilder {
      // Use PicPlot.newBuilder() to construct.
      private PicPlot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PicPlot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PicPlot defaultInstance;
      public static PicPlot getDefaultInstance() {
        return defaultInstance;
      }

      public PicPlot getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PicPlot(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                dataname_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                scirptname_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                picname_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Vs.internal_static_VisualConfig_PicPlot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Vs.internal_static_VisualConfig_PicPlot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Vs.VisualConfig.PicPlot.class, Vs.VisualConfig.PicPlot.Builder.class);
      }

      public static com.google.protobuf.Parser<PicPlot> PARSER =
          new com.google.protobuf.AbstractParser<PicPlot>() {
        public PicPlot parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PicPlot(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PicPlot> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DATANAME_FIELD_NUMBER = 1;
      private java.lang.Object dataname_;
      /**
       * <code>required string dataname = 1;</code>
       */
      public boolean hasDataname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dataname = 1;</code>
       */
      public java.lang.String getDataname() {
        java.lang.Object ref = dataname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataname_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string dataname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDatanameBytes() {
        java.lang.Object ref = dataname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCIRPTNAME_FIELD_NUMBER = 2;
      private java.lang.Object scirptname_;
      /**
       * <code>required string scirptname = 2;</code>
       */
      public boolean hasScirptname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string scirptname = 2;</code>
       */
      public java.lang.String getScirptname() {
        java.lang.Object ref = scirptname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            scirptname_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string scirptname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getScirptnameBytes() {
        java.lang.Object ref = scirptname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scirptname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PICNAME_FIELD_NUMBER = 3;
      private java.lang.Object picname_;
      /**
       * <code>required string picname = 3;</code>
       */
      public boolean hasPicname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string picname = 3;</code>
       */
      public java.lang.String getPicname() {
        java.lang.Object ref = picname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            picname_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string picname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPicnameBytes() {
        java.lang.Object ref = picname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        dataname_ = "";
        scirptname_ = "";
        picname_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDataname()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasScirptname()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPicname()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDatanameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getScirptnameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getPicnameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDatanameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getScirptnameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getPicnameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Vs.VisualConfig.PicPlot parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Vs.VisualConfig.PicPlot parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Vs.VisualConfig.PicPlot parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Vs.VisualConfig.PicPlot parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Vs.VisualConfig.PicPlot prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code VisualConfig.PicPlot}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:VisualConfig.PicPlot)
          Vs.VisualConfig.PicPlotOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Vs.internal_static_VisualConfig_PicPlot_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Vs.internal_static_VisualConfig_PicPlot_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Vs.VisualConfig.PicPlot.class, Vs.VisualConfig.PicPlot.Builder.class);
        }

        // Construct using Vs.VisualConfig.PicPlot.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          dataname_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          scirptname_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          picname_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Vs.internal_static_VisualConfig_PicPlot_descriptor;
        }

        public Vs.VisualConfig.PicPlot getDefaultInstanceForType() {
          return Vs.VisualConfig.PicPlot.getDefaultInstance();
        }

        public Vs.VisualConfig.PicPlot build() {
          Vs.VisualConfig.PicPlot result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Vs.VisualConfig.PicPlot buildPartial() {
          Vs.VisualConfig.PicPlot result = new Vs.VisualConfig.PicPlot(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.dataname_ = dataname_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.scirptname_ = scirptname_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.picname_ = picname_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Vs.VisualConfig.PicPlot) {
            return mergeFrom((Vs.VisualConfig.PicPlot)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Vs.VisualConfig.PicPlot other) {
          if (other == Vs.VisualConfig.PicPlot.getDefaultInstance()) return this;
          if (other.hasDataname()) {
            bitField0_ |= 0x00000001;
            dataname_ = other.dataname_;
            onChanged();
          }
          if (other.hasScirptname()) {
            bitField0_ |= 0x00000002;
            scirptname_ = other.scirptname_;
            onChanged();
          }
          if (other.hasPicname()) {
            bitField0_ |= 0x00000004;
            picname_ = other.picname_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDataname()) {
            
            return false;
          }
          if (!hasScirptname()) {
            
            return false;
          }
          if (!hasPicname()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Vs.VisualConfig.PicPlot parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Vs.VisualConfig.PicPlot) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object dataname_ = "";
        /**
         * <code>required string dataname = 1;</code>
         */
        public boolean hasDataname() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string dataname = 1;</code>
         */
        public java.lang.String getDataname() {
          java.lang.Object ref = dataname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              dataname_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string dataname = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDatanameBytes() {
          java.lang.Object ref = dataname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            dataname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string dataname = 1;</code>
         */
        public Builder setDataname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          dataname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string dataname = 1;</code>
         */
        public Builder clearDataname() {
          bitField0_ = (bitField0_ & ~0x00000001);
          dataname_ = getDefaultInstance().getDataname();
          onChanged();
          return this;
        }
        /**
         * <code>required string dataname = 1;</code>
         */
        public Builder setDatanameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          dataname_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object scirptname_ = "";
        /**
         * <code>required string scirptname = 2;</code>
         */
        public boolean hasScirptname() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string scirptname = 2;</code>
         */
        public java.lang.String getScirptname() {
          java.lang.Object ref = scirptname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              scirptname_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string scirptname = 2;</code>
         */
        public com.google.protobuf.ByteString
            getScirptnameBytes() {
          java.lang.Object ref = scirptname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            scirptname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string scirptname = 2;</code>
         */
        public Builder setScirptname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          scirptname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string scirptname = 2;</code>
         */
        public Builder clearScirptname() {
          bitField0_ = (bitField0_ & ~0x00000002);
          scirptname_ = getDefaultInstance().getScirptname();
          onChanged();
          return this;
        }
        /**
         * <code>required string scirptname = 2;</code>
         */
        public Builder setScirptnameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          scirptname_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object picname_ = "";
        /**
         * <code>required string picname = 3;</code>
         */
        public boolean hasPicname() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string picname = 3;</code>
         */
        public java.lang.String getPicname() {
          java.lang.Object ref = picname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              picname_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string picname = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPicnameBytes() {
          java.lang.Object ref = picname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            picname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string picname = 3;</code>
         */
        public Builder setPicname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          picname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string picname = 3;</code>
         */
        public Builder clearPicname() {
          bitField0_ = (bitField0_ & ~0x00000004);
          picname_ = getDefaultInstance().getPicname();
          onChanged();
          return this;
        }
        /**
         * <code>required string picname = 3;</code>
         */
        public Builder setPicnameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          picname_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:VisualConfig.PicPlot)
      }

      static {
        defaultInstance = new PicPlot(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:VisualConfig.PicPlot)
    }

    public static final int CHARTS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList charts_;
    /**
     * <code>repeated string charts = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getChartsList() {
      return charts_;
    }
    /**
     * <code>repeated string charts = 1;</code>
     */
    public int getChartsCount() {
      return charts_.size();
    }
    /**
     * <code>repeated string charts = 1;</code>
     */
    public java.lang.String getCharts(int index) {
      return charts_.get(index);
    }
    /**
     * <code>repeated string charts = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChartsBytes(int index) {
      return charts_.getByteString(index);
    }

    public static final int PICS_FIELD_NUMBER = 2;
    private java.util.List<Vs.VisualConfig.PicPlot> pics_;
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    public java.util.List<Vs.VisualConfig.PicPlot> getPicsList() {
      return pics_;
    }
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    public java.util.List<? extends Vs.VisualConfig.PicPlotOrBuilder> 
        getPicsOrBuilderList() {
      return pics_;
    }
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    public int getPicsCount() {
      return pics_.size();
    }
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    public Vs.VisualConfig.PicPlot getPics(int index) {
      return pics_.get(index);
    }
    /**
     * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
     */
    public Vs.VisualConfig.PicPlotOrBuilder getPicsOrBuilder(
        int index) {
      return pics_.get(index);
    }

    private void initFields() {
      charts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      pics_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPicsCount(); i++) {
        if (!getPics(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < charts_.size(); i++) {
        output.writeBytes(1, charts_.getByteString(i));
      }
      for (int i = 0; i < pics_.size(); i++) {
        output.writeMessage(2, pics_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < charts_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(charts_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getChartsList().size();
      }
      for (int i = 0; i < pics_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pics_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Vs.VisualConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Vs.VisualConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Vs.VisualConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Vs.VisualConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Vs.VisualConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Vs.VisualConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Vs.VisualConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Vs.VisualConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Vs.VisualConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Vs.VisualConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Vs.VisualConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VisualConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VisualConfig)
        Vs.VisualConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Vs.internal_static_VisualConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Vs.internal_static_VisualConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Vs.VisualConfig.class, Vs.VisualConfig.Builder.class);
      }

      // Construct using Vs.VisualConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPicsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        charts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (picsBuilder_ == null) {
          pics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          picsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Vs.internal_static_VisualConfig_descriptor;
      }

      public Vs.VisualConfig getDefaultInstanceForType() {
        return Vs.VisualConfig.getDefaultInstance();
      }

      public Vs.VisualConfig build() {
        Vs.VisualConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Vs.VisualConfig buildPartial() {
        Vs.VisualConfig result = new Vs.VisualConfig(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          charts_ = charts_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.charts_ = charts_;
        if (picsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pics_ = java.util.Collections.unmodifiableList(pics_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pics_ = pics_;
        } else {
          result.pics_ = picsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Vs.VisualConfig) {
          return mergeFrom((Vs.VisualConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Vs.VisualConfig other) {
        if (other == Vs.VisualConfig.getDefaultInstance()) return this;
        if (!other.charts_.isEmpty()) {
          if (charts_.isEmpty()) {
            charts_ = other.charts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChartsIsMutable();
            charts_.addAll(other.charts_);
          }
          onChanged();
        }
        if (picsBuilder_ == null) {
          if (!other.pics_.isEmpty()) {
            if (pics_.isEmpty()) {
              pics_ = other.pics_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePicsIsMutable();
              pics_.addAll(other.pics_);
            }
            onChanged();
          }
        } else {
          if (!other.pics_.isEmpty()) {
            if (picsBuilder_.isEmpty()) {
              picsBuilder_.dispose();
              picsBuilder_ = null;
              pics_ = other.pics_;
              bitField0_ = (bitField0_ & ~0x00000002);
              picsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPicsFieldBuilder() : null;
            } else {
              picsBuilder_.addAllMessages(other.pics_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPicsCount(); i++) {
          if (!getPics(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Vs.VisualConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Vs.VisualConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList charts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChartsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          charts_ = new com.google.protobuf.LazyStringArrayList(charts_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getChartsList() {
        return charts_.getUnmodifiableView();
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public int getChartsCount() {
        return charts_.size();
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public java.lang.String getCharts(int index) {
        return charts_.get(index);
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChartsBytes(int index) {
        return charts_.getByteString(index);
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public Builder setCharts(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChartsIsMutable();
        charts_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public Builder addCharts(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChartsIsMutable();
        charts_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public Builder addAllCharts(
          java.lang.Iterable<java.lang.String> values) {
        ensureChartsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, charts_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public Builder clearCharts() {
        charts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string charts = 1;</code>
       */
      public Builder addChartsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChartsIsMutable();
        charts_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<Vs.VisualConfig.PicPlot> pics_ =
        java.util.Collections.emptyList();
      private void ensurePicsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pics_ = new java.util.ArrayList<Vs.VisualConfig.PicPlot>(pics_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Vs.VisualConfig.PicPlot, Vs.VisualConfig.PicPlot.Builder, Vs.VisualConfig.PicPlotOrBuilder> picsBuilder_;

      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public java.util.List<Vs.VisualConfig.PicPlot> getPicsList() {
        if (picsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pics_);
        } else {
          return picsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public int getPicsCount() {
        if (picsBuilder_ == null) {
          return pics_.size();
        } else {
          return picsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Vs.VisualConfig.PicPlot getPics(int index) {
        if (picsBuilder_ == null) {
          return pics_.get(index);
        } else {
          return picsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder setPics(
          int index, Vs.VisualConfig.PicPlot value) {
        if (picsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePicsIsMutable();
          pics_.set(index, value);
          onChanged();
        } else {
          picsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder setPics(
          int index, Vs.VisualConfig.PicPlot.Builder builderForValue) {
        if (picsBuilder_ == null) {
          ensurePicsIsMutable();
          pics_.set(index, builderForValue.build());
          onChanged();
        } else {
          picsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder addPics(Vs.VisualConfig.PicPlot value) {
        if (picsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePicsIsMutable();
          pics_.add(value);
          onChanged();
        } else {
          picsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder addPics(
          int index, Vs.VisualConfig.PicPlot value) {
        if (picsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePicsIsMutable();
          pics_.add(index, value);
          onChanged();
        } else {
          picsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder addPics(
          Vs.VisualConfig.PicPlot.Builder builderForValue) {
        if (picsBuilder_ == null) {
          ensurePicsIsMutable();
          pics_.add(builderForValue.build());
          onChanged();
        } else {
          picsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder addPics(
          int index, Vs.VisualConfig.PicPlot.Builder builderForValue) {
        if (picsBuilder_ == null) {
          ensurePicsIsMutable();
          pics_.add(index, builderForValue.build());
          onChanged();
        } else {
          picsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder addAllPics(
          java.lang.Iterable<? extends Vs.VisualConfig.PicPlot> values) {
        if (picsBuilder_ == null) {
          ensurePicsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pics_);
          onChanged();
        } else {
          picsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder clearPics() {
        if (picsBuilder_ == null) {
          pics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          picsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Builder removePics(int index) {
        if (picsBuilder_ == null) {
          ensurePicsIsMutable();
          pics_.remove(index);
          onChanged();
        } else {
          picsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Vs.VisualConfig.PicPlot.Builder getPicsBuilder(
          int index) {
        return getPicsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Vs.VisualConfig.PicPlotOrBuilder getPicsOrBuilder(
          int index) {
        if (picsBuilder_ == null) {
          return pics_.get(index);  } else {
          return picsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public java.util.List<? extends Vs.VisualConfig.PicPlotOrBuilder> 
           getPicsOrBuilderList() {
        if (picsBuilder_ != null) {
          return picsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pics_);
        }
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Vs.VisualConfig.PicPlot.Builder addPicsBuilder() {
        return getPicsFieldBuilder().addBuilder(
            Vs.VisualConfig.PicPlot.getDefaultInstance());
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public Vs.VisualConfig.PicPlot.Builder addPicsBuilder(
          int index) {
        return getPicsFieldBuilder().addBuilder(
            index, Vs.VisualConfig.PicPlot.getDefaultInstance());
      }
      /**
       * <code>repeated .VisualConfig.PicPlot pics = 2;</code>
       */
      public java.util.List<Vs.VisualConfig.PicPlot.Builder> 
           getPicsBuilderList() {
        return getPicsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Vs.VisualConfig.PicPlot, Vs.VisualConfig.PicPlot.Builder, Vs.VisualConfig.PicPlotOrBuilder> 
          getPicsFieldBuilder() {
        if (picsBuilder_ == null) {
          picsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Vs.VisualConfig.PicPlot, Vs.VisualConfig.PicPlot.Builder, Vs.VisualConfig.PicPlotOrBuilder>(
                  pics_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pics_ = null;
        }
        return picsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VisualConfig)
    }

    static {
      defaultInstance = new VisualConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VisualConfig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisualConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VisualConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisualConfig_PicPlot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VisualConfig_PicPlot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010vs.proto\"\205\001\n\014VisualConfig\022\016\n\006charts\030\001 " +
      "\003(\t\022#\n\004pics\030\002 \003(\0132\025.VisualConfig.PicPlot" +
      "\032@\n\007PicPlot\022\020\n\010dataname\030\001 \002(\t\022\022\n\nscirptn" +
      "ame\030\002 \002(\t\022\017\n\007picname\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VisualConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisualConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VisualConfig_descriptor,
        new java.lang.String[] { "Charts", "Pics", });
    internal_static_VisualConfig_PicPlot_descriptor =
      internal_static_VisualConfig_descriptor.getNestedTypes().get(0);
    internal_static_VisualConfig_PicPlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VisualConfig_PicPlot_descriptor,
        new java.lang.String[] { "Dataname", "Scirptname", "Picname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
