package:
  name: singa
  version: "1.1.0"

source:
  git_url: https://github.com/nudles/incubator-singa.git
  git_rev: {{ GIT_DESCRIBE_TAG }}


build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python 2.7*
    - numpy >=1.10
    - swig >=3.0
    - openblas >=0.2.10
    - protobuf >=2.5,<2.7
    - cmake >=2.8

  run:
    - python 2.7*
    - numpy >=1.10
    - protobuf >=2.5,<3.0
    - openblas >=0.2.10
    - flask >=0.10.1
    - flask_cors >=3.0.2
    - pillow>=2.3.0
    - unittest-xml-reporting

about:
  home: http://singa.apache.org/
  license: Apache V2
  license_file: LICENSE
